== OpenShift S2I Builder for Java

SHAMELESS RIP FROM: https://github.com/welshstew/s2i-gradle

Just toying with this so I can:

- Clone a repo containing a gradle project (containing a load of scripts)
- 


This Source-to-Image Builder let's you create projects targetting Java OpenJDK 8 and built with:

* maven
* gradle

NOTE: If a project has a pom.xml and a build.gradle, maven will take precedence

This builder/runtime s2i image can be used with SpringBoot, Vert.X, Wildfly Swarm, DropWizard and many other microservices frameworks. 

== BUILD ENV Options

* *APP_SUFFIX*: Jar file suffix to use to locate the generated artifact to use (e.g. xxxxx${APP_SUFFIX}.jar)
* *BUILDER_ARGS*: Allows you to specify options to pass to maven or gradle

== RUN ENV Options

* *APP_OPTIONS*: Options to pass to *java -jar app.jar ${APP_OPTIONS}*


== Defaults
If you do not specify any BUILDER_ARGS, by default the s2i image will use the following:

* Maven

----
BUILDER_ARGS="package -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga"
----

* Gradle

----
BUILDER_ARGS="build -x test"
----

== Test in OpenShift

* First load all the needed resources in a project.

----
oc create -f https://raw.githubusercontent.com/welshstew/s2i-gradle/master/ose3/s2i-gradle-imagestream.json
----

* Once the builder s2i-gradle has been registered, you can create an app with:

** Instant app already provided as template
** Using the s2i-gradle builder image using a regular Git repository

== Samples
There is a lot of example SpringBoot applications https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples[here]
